name: sshh
on: push
jobs:
  ssh:
    runs-on: ubuntu-20.04

    steps:
      - name: unblock 15 min
        run: touch /tmp/keepalive

      - name: Setup Debug Session
        uses: csexton/debugger-action@master
